- name: Create database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    state: present
    name: "{{ item.name }}"

- name: Create user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    state: present
    db: "{{ item.name }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    priv: ALL
