---
- name: Get exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus-community/postgres_exporter/releases/download/v0.11.1/postgres_exporter-0.11.1.linux-amd64.tar.gz
    dest: /opt/
    remote_src: true

- name: Set up exporter systemd service
  ansible.builtin.template:
    dest: /etc/systemd/system/postgres-exporter.service
    src: exporter.service
    mode: 0644
  notify:
    - restart exporter

- name: Reload systemd daemon
  ansible.builtin.systemd:
    name: postgres-exporter
    enabled: true
    daemon_reload: true
