- name: Install packages
  ansible.builtin.include_tasks: packages.yml
  tags:
    - packages

- name: Configure Postgres
  ansible.builtin.include_tasks: pg_config.yml
  tags:
    - postgres

- name: Set up databases
  ansible.builtin.include_tasks: databases.yml
  loop: "{{ postgres_databases }}"
  tags:
    - databases

- name: Install Prometheus exporter
  ansible.builtin.include_tasks: exporter.yml
  tags:
    - exporter

- name: Allow access from Docker containers
  community.general.ufw:
    rule: allow
    proto: tcp
    from_ip: "{{ item }}"
    to_ip: any
    to_port: "5432"
  with_items:
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  notify:
    - Restart ufw
