- name: Add postgres repository key
  ansible.builtin.apt_key:
    state: present
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add postgres repository
  ansible.builtin.apt_repository:
    state: present
    repo: deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main

- name: Install packages
  ansible.builtin.apt:
    state: present
    name:
      - libpq-dev
      - python3-psycopg2
      - postgresql-14
