---
- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: restart exporter
  service:
    name: postgres-exporter
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted
