- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Restart exporter
  ansible.builtin.service:
    name: postgres-exporter
    state: restarted

- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted
